server:
  port: 8080
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret
  datasource:
    url: jdbc:neo4j:${spring.neo4j.uri}
    username: ${spring.neo4j.authentication.username}
    password: ${spring.neo4j.authentication.password}
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml