server:
  port: 8080
spring:
  neo4j:
    uri: ${DATASOURCE_URI:bolt://localhost:7687}
    authentication:
      username: ${DATASOURCE_USERNAME:neo4j}
      password: ${DATASOURCE_PASSWORD:secret}
  datasource:
    url: ${DATASOURCE_URL:jdbc:neo4j:${spring.neo4j.uri}}
    username: ${spring.neo4j.authentication.username}
    password: ${spring.neo4j.authentication.password}
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
user:
  start-gold: 100
security-custom:
  jwt-token:
    jwt-secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    jwt-issuer: IW
    jwt-expiration: 7200000  # 2 hours
  refresh-token:
    expiration: 604800000 # 7 days