server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_empty
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret
  datasource:
    url: jdbc:neo4j:${spring.neo4j.uri}
    username: ${spring.neo4j.authentication.username}
    password: ${spring.neo4j.authentication.password}
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: user-ingredient
      acks: all
      bootstrap-servers: localhost:9092
user:
  start-gold: 100
security-custom:
  jwt-token:
    jwt-secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    jwt-issuer: IW
    jwt-expiration: 7200000  # 2 hours
  refresh-token:
    expiration: 604800000 # 7 days
open_api:
  paths:
    user_path:
      /api/v1/user/**
    ingredient_path:
      /api/v1/ingredient/**
    user_ingredient_path:
      /api/v1/user_ingredient/**
kafka:
  topic:
    name: "notification_topic"
    partitions: 10
    replicas: 1
task_custom:
  execution:
    pool:
      core-size: 5
      max-size: 10
      queue-capacity: 25
    shutdown:
      await-termination: true